### ISSUE TITLE
Intermittent silent crashing of camera service during take_exposure

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#252]
For some reason, the camera services on (all?) the pis have crashed a few (most but not all) times during `camera.take_exposure`. A minority of exposures succeed. Not much in the logs. The last message in the camera  logs is about a `panoptes.utils` countdown timer being reset.

This problem persists for blocking and non-blocking exposures, and doesn't depend on whether the file gets written in the SSHFS directory.

The camera service logs:
```
D 12-08 23:28:08.08 (23:28:08.08) | panoptes.pocs.camera.camera take_exposure:485 │·····························································································
                   | Taking seconds=<Quantity 1. s> exposure on 192.168.80.140: fi│·····························································································
lename='/home/huntsman/test_huntsmanpi000_00.fits'                                │·····························································································
D 12-08 23:28:10.10 (23:28:10.10) | panoptes.pocs.camera.libasi set_control_value:│·····························································································
238                | Set EXPOSURE to 1.0 s on camera 0                            │·····························································································
D 12-08 23:28:10.10 (23:28:10.10) | panoptes.pocs.camera.libasi start_exposure:450│·····························································································
                   | Exposure started on camera 0                                 │·····························································································
D 12-08 23:28:10.10 (23:28:10.10) | panoptes.utils.time restart:164               │·····························································································
                   | Restarting Timer (blocking) 30.10/30.10                      │·····························································································
I 12-08 23:28:14.14 (23:28:14.14) | huntsman.pocs.utils.pyro.cli service:93       │·····························································································
               | Pyro huntsmanpi000 shut down.
```

In the camera service window:
```
I 12-08 23:27:17.17 Pyro service huntsmanpi000 started. Ctrl-C/Cmd-C to quit...   │·····························································································
I 12-08 23:27:58.58 Moving ZWO Filter Wheel (2) [Camera: 192.168.80.140] to positi│·····························································································
on 3 (g_band)                                                                     │·····························································································
I 12-08 23:28:00.00 Moving ZWO Filter Wheel (2) [Camera: 192.168.80.140] to positi│·····························································································
on 1 (blank)                                                                      │·····························································································
I 12-08 23:28:05.05 Moving ZWO Filter Wheel (2) [Camera: 192.168.80.140] to positi│·····························································································
on 3 (g_band)                                                                     │·····························································································
I 12-08 23:28:14.14 Pyro huntsmanpi000 shut down.
```

Error message on the client side (control computer):
```
Exception in thread Thread-2:                                                                                                      │···········
Traceback (most recent call last):                                                                                                 │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/socketutil.py", line 132, in receive_data                            │···········
    chunk = sock.recv(size, socket.MSG_WAITALL)                                                                                    │···········
ConnectionResetError: [Errno 104] Connection reset by peer                                                                         │···········
                                                                                                                                   │···········
During handling of the above exception, another exception occurred:                                                                │···········
                                                                                                                                   │···········
Traceback (most recent call last):                                                                                                 │···········
  File "/var/panoptes/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner                                             │···········
    self.run()                                                                                                                     │···········
  File "/var/panoptes/conda/lib/python3.7/threading.py", line 870, in run                                                          │···········
    self._target(*self._args, **self._kwargs)                                                                                      │···········
  File "/var/huntsman/huntsman-pocs/src/huntsman/pocs/camera/pyro/client.py", line 266, in _wait_for_readout                       │···········
    if not proxy.is_reading_out:                                                                                                   │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/client.py", line 94, in __getattr__                                  │···········
    return self._pyroInvoke("__getattr__", (name,), None)                                                                          │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/client.py", line 224, in _pyroInvoke                                 │···········
    msg = protocol.recv_stub(self._pyroConnection, [protocol.MSG_RESULT])                                                          │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/protocol.py", line 189, in recv_stub                                 │···········
    header = connection.recv(6)  # 'PYRO' + 2 bytes protocol version                                                               │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/socketutil.py", line 435, in recv                                    │···········
    return receive_data(self.sock, size)                                                                                           │···········
  File "/var/panoptes/conda/lib/python3.7/site-packages/Pyro5/socketutil.py", line 144, in receive_data                            │···········
    raise ConnectionClosedError("receiving: connection lost: " + str(x))                                                           │···········
Pyro5.errors.ConnectionClosedError: receiving: connection lost: [Errno 104] Connection reset by peer
```

I provide additional details here ASAP.

**Comment by danjampro** [comment]
Closing after fix - see #255
