### ISSUE TITLE
Camera timeouts during flat fielding kill state machine

### ISSUE THREAD

**Issue by danjampro** [wtgee/huntsman-pocs#349]
```E 02-10 22:21:16.180 Timeout: 76.86261083691309 reached for filename='images/flat/0f1d420013090900/20211009T083049/flat_004.fits' to exist on 192.168.80.148 (0f1d420013090900) port=huntsmanpi008.
Exception in thread Thread-HUNTS01_0f1d420013090900_20211009T083357:
Traceback (most recent call last):
  File "/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/conda/lib/python3.8/site-packages/huntsman/pocs/camera/pyro/client.py", line 296, in process_exposure
    self._exposure_future.result()
  File "/conda/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/conda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conda/lib/python3.8/site-packages/huntsman/pocs/camera/pyro/client.py", line 323, in _wait_for_file
    raise error.Timeout(f"{timeout!r} reached for {filename=} to exist on {self}.")
panoptes.utils.error.Timeout: Timeout: 76.86261083691309 reached for filename='images/flat/0f1d420013090900/20211009T083049/flat_004.fits' to exist on 192.168.80.148 (0f1d420013090900) port=huntsmanpi008.
E 02-10 22:21:36.127 Timeout: Timeout while waiting for camera event on huntsmanpi008.
C 02-10 22:21:36.131 Problem going from 'twilight_flat_fielding' to 'parking', exiting loop [Timeout('Timeout while waiting for camera event on huntsmanpi008.')]
S 02-10 22:21:36.135 Stopping POCS states
I 02-10 22:21:36.139 Calling set_config on  url='http://localhost:6563/set-config'
```

**Comment by danjampro** [comment]
Closed by ???
